# Generated by Django 4.1.5 on 2023-02-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profersores',
            new_name='profesores',
        ),
        migrations.DeleteModel(
            name='entregable',
        ),
    ]
